### PR TITLE
Improve output and documentation

### LINKED ISSUE #108: `nerd task start` should be `nerd task create`
I find it really confusing that this is start. -- taking this action doesn't actually stat the task, I think 'starting' should be reserved for workloads (and workers).

### LINKED ISSUE #125: show which project is active
on the CLI, at 'nerd project list' show which project is active

### LINKED ISSUE #138: Usage of dataset upload command is wrongly documented in spec
The usage of `nerd dataset upload` is documented as `nerd upload`.
See spec.json: https://github.com/nerdalize/nerd/blob/4927bd06b73c6fe731232e46254e042d89912ca6/spec.json#L61

Should be `nerd dataset upload`, no?

### LINKED ISSUE #147: nerd workload start has old options
`-w` is still shown in help, but it's an old option

### LINKED ISSUE #153: Output is not clear when not logged in
When I want a list of my projects but I'm not logged in, I get a unclear error. I would expect an error explaining that I'm not logged in.
```
$ nerd project list
failed to list projects
$ nerd secret create quay.io test=test                                                   
You are not logged in. Please login using 'nerd login'
```

### LINKED ISSUE #155: If a user tries to set a project that doesn't exist, an error should be returned.
After a test, if we run `nerd project set 213`, it will set it in the config.json, and the user will have to wait to run another command to get an error (which is not really clear itself). 
```
$ nerd project set test                                                                
$ nerd secret create quay.io test=test
failed to get placement: failed to get database item: no such placement
```

### PR DESCRIPTION
**Pull request by LilliJane**
+ Secret commands now use the new output format
+ `nerd project list` indicates which project is the current one
+ `nerd task start` becomes `nerd task create`
+ Documentation updated
+ Update dependencies
+ Remove logrus dependency

This pull request closes #108, closes #147, closes #125, closes #138, closes #155 and closes #153.

### CODE REVIEW

**Comment by LilliJane** [comment]
I added some error handling in case the user is not logged in or the project is not set.
Also, for the secrets, each command now checks if the project is set. Before, `nerd secret list|create|delete|describe` had a `page not found` output (it was trying to create a path without the project name).

**Comment by dhrp** [comment]
## General
### Help
The help for secrets string is too long.. It should be about as long as the others (perhaps + a bit)

```
Available commands are:
    dataset     Upload and download datasets for tasks to use.
    login       Start a new authorized session.
    project     Set and list projects.
    secret      Set and list secrets. A secret can be credentials for a Docker registry, or other sensitive information needed by your project.
    task        Manage the lifecycle of compute tasks.
    version     Check the current version.
    worker      Control individual compute processes.
    workload    Control compute capacity for working on tasks.
```

## Secrets
### I don't understand why this isn't valid.
```
Oatcake:nerd thatcher$ ./main secret create name=thatcher
provide a valid key value pair: key=value
```
I see now.. It's because I omitted the secret name. Perhaps we can detect that there is a '=' character in the supposed name, and tell people the name is missing (instead of the key).

### The format here is not well-aligned (name has more spaces)
```
Oatcake:nerd thatcher$ ./main secret describe thatchers
Secret Details:
Name:               thatchers
Type:          Opaque
Key:           name
Value:         bob
```

### Help inconsistent:

In this help block I would like to see the mention that I can specify type registry. Probably adding another example of usage (on top) would help a lot. Also a mention that you can use the name of the registry as name..

```
Usage:
  nerd secret create <name> [key=val] [OPTIONS]

options:
      --username=                Username for Docker registry authentication
      --password=                Password for Docker registry authentication
      --type=                    Type of secret to display (default: opaque)
```


### Output ugly
The output of this registry secret is not so pretty...

```
Oatcake:nerd thatcher$ ./main secret describe quay.io
Secret Details:
Name:               quay.io
Type:          kubernetes.io/dockerconfigjson
Key:           .dockerconfigjson
Value:         {&#34;HttpHeaders&#34;:{&#34;User-Agent&#34;:&#34;Docker-Client/1.11.2 (linux)&#34;},&#34;auths&#34;:{&#34;https://quay.io/v1/&#34;:{&#34;auth&#34;:&#34;ZGhy[...]mJR&#34;},&#34;quay.io&#34;:{&#34;auth&#34;:&#34;ZGhy[...]emJR&#34;}}}
```

**Comment by LilliJane** [comment]
@dhrp I updated the `nerd secret create` helper and fixed the issues you found

**Comment by dhrp** [comment]
What about:

`$ nerd secret create`

```
Not enough arguments, see below for usage.

Create secrets
A secret can contain either credentials for a registry, or a one or multiple 
key-value pairs that will be made available in your worker.

Usage:
  nerd secret create <registry> --type registry --username <user> --password <pwd>
   OR
  nerd secret create <name-for-secret> <key=value> [more]

options:
      --username=                Username for Docker registry authentication
      --password=                Password for Docker registry authentication
      --type=                    Type of secret to display (default: opaque)

Output options:
      --config-file=             Location of config file [$NERD_CONFIG_FILE]
      --session-file=            Location of session file [$NERD_SESSION_FILE]
      --debug=                   Show debug output (default: false) [$NERD_DEBUG]
      --output=[pretty|raw|json] Format of the output (default: pretty)

Help Options:
  -h, --help                     Show this help message
```

We should try to not go past the 80-characters on a line.

**Comment by LilliJane** [comment]
Why can't we keep the description on one line? It would split automatically if it's used with an 80-character wide window. But I agree for the usage, it's clearer like that.

**Comment by dhrp** [comment]
The line wrapping doesn't look nice on my terminal. 

screenshot 2017-08-30 13 01 39

**Comment by dhrp** [comment]
LGTM. I can't merge it though because of conflicts.

**Pull request merged**
