### PR TITLE
Improve dev environment

### LINKED ISSUE #223: Install a  CustomResourceDefinition for datasets during development
The basic idea is that we use Kubernetes [Custom Resources](https://kubernetes.io/docs/concepts/api-extension/custom-resources/) to store datasets in the kubernetes clusters. These dataset resources store metadata and are (a) reference(s) to were the actual data (blobs) lives. For now we only support our public-s3-sandbox-without-deduplication as a place for actual storage but in the future more can be supported. In terms of Metadata we would mostly want the size of a dataset to be stored but in the future one can image tags or up/down progress information to be available in dataset resources as well.

As an example the custom resource definition could look like this, take from [here](https://github.com/kubernetes/sample-controller/tree/master/artifacts/examples), also see: [here](https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/):
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: datasets.nerdalize.com
spec:
  group: nerdalize.com
  version: v1alpha1
  names:
    kind: Dataset
    plural: datasets
    shortNames:
    - ds
  scope: Namespaced
```

We would this definition to be available on the cluster we're developing for before we can begin.

### LINKED ISSUE #238: In the development environment make sure a namespace is set
## Expected Behavior
When no kube config is on the system, running the test suite should be enough to get the CLI to work after a build.

## Actual Behavior
Currently returns an error complaining about project not set:
```
error: No project ID specified, use `nerd project set` to configure a project to work on.
```

## Solution
Make sure a namespace is set upon testing

### PR DESCRIPTION
**Pull request by LilliJane**
Now, the `./make.sh test` command setup a complete context in the kube config file, set up custom resource definition for datasets but also check that the generate code for this crd is up to date.

One other command has been added, `./make.sh dev`. This command sets up the kube config file, sets up the crd for datasets, updates the repo dependencies and checks if the crd generated code is still valid. 

For both commands, if the generated code is not anymore up to date, the script will update it.

Closes #223 and closes #238

### CODE REVIEW

**Comment by advanderveer** [comment]
Nice! I've fixed the if statement that checks the return code to determine if we need to re-generate the code. I think the script always exists if the return code was non-zero (due to `set -e` at the top). If you test it still works on your machine we can merge this

**Comment by LilliJane** [comment]
Thanks! Do you think we should also start minikube with the `./make.sh dev` command ?

**Comment by advanderveer** [comment]
Added the same fix to the dev command didn't notice the changes there yet. Maybe the run_test command should the command every developer runs to get up to speed? then we also don't have duplicate logic between run_dev and run_test?

**Comment by LilliJane** [comment]
I divided the logic between `./make.sh test` and `./make.sh dev`. Now `./make.sh test` runs only the tests and `./make.sh dev` is the go-to command to setup a proper development environment

**Pull request merged**
