### PR TITLE
Minimal viable Job Running

### PR DESCRIPTION
**Pull request by advanderveer**
For milestone 1.1 it will be possible to directly run a Job on a Kubernetes cluster. This pull request contains the effort for getting this to work. This should complete both #190 and #189 

- [x] It should be possible to start a Job with just an image
- [x] No custom names yet
- [x] no args or env yet
- [x] make sure we have one button test with minikube
- [x] settle on a simple but extensible way of handling kubernetes errors
- [x] by default load kube credentials from the `~/.kube/config` directory with an option to customize. might become more eleborate with #187 
- [x] add an option that determines the kubernetes namespace, load from a configuration with #187
- [x] add an option that decides on a default timeout value for Kubernetes requests
- [x] add a nerd prefix to jobs that is transparently stripped for users to only show cli managed jobs
- [x] add some logging for the kube service

### CODE REVIEW

**Comment by advanderveer** [comment]
## Iteration 2 
First new CLI version will be the first stepping stone to an improved experience. The following will be supported:

### Running a Job
```
$ nerd job run --name=experiment2 quay.io/nerdalize/delft3d 
job 'experiment2' was submitted, use `nerd job list` to see its status
```

### Listing Jobs
```
$ nerd job list
PROJECT             NAME                  STATUS
joost-default       my-test               pending:  No node available for scheduling
joost-default        experiment1       failed: Image 'xyz' does not exist
joost-default        experiment2      RUNNING
```

### Viewing Job Logs
```
$ nerd job logs experiment2
[12:33] Lorum ipsum
[13:34] Lorum ipsum
```

**Comment by alexanderweiss** [comment]
Nice! Can we have more consistent formatting of the status though ☺️?

**Comment by Maaikest** [comment]
Nice! A few suggestions:
- instead of  'nerd job fix' use 'nerd job update' for a more positive tone?
- in 'nerd job list' maybe use 'JOB'  or 'JOB-NAME' instead of 'NAME'?

I like that the 'nerd job list' lists all jobs in all projects!

And maybe we can discuss the display of usage in 'nerd project usage'? 
- Give info on if the project is currently consuming capacity
- '4 hours of 10 compute units' feels more clear to me
- And I guess people have to specify the project in 'nerd project usage' or do they get a list of all projects?
- And would they know whether the project is still in the free plan?

**Comment by advanderveer** [comment]
Nice suggestions: 
 -fix was proposed to give it more of a hint at what it could be used for and update is so boring but I agree that 'update' can be applied more generic: (what if nothing is broken but I want to change something anyway.
- Agreed on giving more context than just name, "JOB"  is sweet and short i would say

Usage feedback is still rough and fully open, I would argue that it should fit into the mental model our users have after having looked at our pricing or usage so maybe display it the same as over there?

**Pull request merged**
