### PR TITLE
Fix quota payloads

### PR DESCRIPTION
**Pull request by LilliJane**
Updated payloads to match with universe billing package controller

### CODE REVIEW

**Comment by advanderveer** [comment]
I don't think we should add kubernetes as a dependency to the nerd repository just for the resource struct. Is there an alternative that is worth considering?

**Comment by LilliJane** [comment]
Kubernetes is not a dependency here, the `Resource` struct is our own (and contains only string fields)

**Comment by advanderveer** [comment]
Are you still looking for feedback here? It looks good to merge

**Comment by LilliJane** [comment]
If it's good for you, then I'll merge it

**Pull request merged**
